services:
    mongodb:
        image: mongo
        restart: always
        ports:
            - 27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
            - MONGO_INITDB_DATABASE=${DB_NAME:-library_db}
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
        depends_on:
            - mongodb
    web:
        build: .
        ports:
            - 80:3000
        environment:
            - PORT=3000
            - DB_USERNAME=${DB_USERNAME:-root}
            - DB_PASSWORD=${DB_PASSWORD:-password}
            - DB_NAME=${DB_NAME:-library_db}
            - DB_HOST=mongodb://mongodb:27017
        depends_on:
            - mongodb