services:
    redis:
        image: redis
    web:
        build: .
        ports:
            - "80:3000"
        environment:
            - PORT=3000
            - REDIS_URL=redis
        links:
            - redis
    counter:
        build: '/home/vitalii/Документы/netology/docker_incr'
        ports:
            - "8080:3001"
        environment:
            - PORT=3001
            - REDIS_URL=redis
        links:
            - redis